server:
    port: 8080

    servlet:
      jsp:
        init-parameters:
          development: true




logging:
        com.example.WChatMonkey: DEBUG
#    tomcat:
#      redirect-context-root:


spring:
    profiles:
       active: dev

    datasource:     # 数据库地址
        url: jdbc:mysql://localhost:3306/eiaproject?useSSL=false
        username: root
        password: ch595200
        driver-class-name: com.mysql.jdbc.Driver


    redis:
      database: 0 # Redis数据库索引（默认为0）
      host: localhost
      port: 6379
      password:

    mvc:
        static:
          static-path-pattern: /**
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp

    servlet:
        multipart:
            max-request-size: 100Mb
            max-file-size: 10Mb

#    rabbitmq:
#        host: localhost
#        port: 5672
#        username: root
#        password: pass
#        publisher-confirms: true

mybatis:
    mapper-locations: classpath:mapper/*.xml,classpath:mapper/assist/*.xml
    typeAliasesPackage: com.gjsyoung.eiaproject.domain #设置别名，xml上可以直接引用，不需要写全类的包路径
    configuration:
      map-underscore-to-camel-case: true  #开启驼峰命名映射，当resultType填写为实体类，而不是BaseResultMap的时候，不会导致有下划线的字段无法映射到对应的属性

#文件上传地址
UploadPath: 'E:\YYYY\eiaproject\out\production\resources\static\'

##上传的最大大小
server.max-http-header-size: 10000000

## rabbitMQ config  发送短信队列
#LogExchange: LogExchange
#LogQueue: LogQueue
#LogRoutingKey: LogRoutingKey

##是否为本地环境,0否 1是
#Local: 0

open: /api/open
authentication: /api/admin